### ISSUE TITLE
Animate torches in the DarkForest scene

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#122]
### Scope
We need to animate the torches in the Dark Forest scene, specifically the fire on each torch. The torches are located in the grid of the scene.
### How to apply?
Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

**Comment by Jemiiah** [comment]
@jimenezz22 pls I would love to work on this issue

**Comment by CristopherAguilar10** [comment]
I would like to participate in this issue, and here’s what I have in mind to implement it. I believe I can set up an Animator for each torch in the Dark Forest scene, applying different fire animation cycles to create a natural, dynamic flickering effect. By adjusting the speed and loop settings of each animation, I can ensure the fire effect aligns naturally with the scene’s mood and atmospheric details. I’ll conduct tests across the grid layout to verify that each torch's fire animation integrates smoothly and enhances the overall aesthetic of the game. Thanks for the opportunity

**Comment by jimenezz22** [comment]
We need to resolve this issue ASAP, Do you think  @CristopherAguilar10 you can solve it in a few hours?

**Comment by CristopherAguilar10** [comment]
@jimenezz22 yes of course, in a couple of hours

**Comment by Jemiiah** [comment]
1. Understand the Scene and Requirements
The issue mentions animating torches specifically to show fire on each torch.
These torches are arranged in a grid within the scene, so your animation will need to scale or be applied to multiple torch elements.
2. Preparation and Research
Check the project’s structure to locate where the DarkForest scene is defined. Look for relevant files that might contain torch elements, such as component files, scene files, or CSS.
Review any existing animations or libraries in the project. If the project is using a library like Three.js or WebGL, it might have tools for animating objects or particles.
3. Creating the Animation
If using CSS Animations:
For simple 2D animations, you can use CSS @keyframes to create a flickering flame effect.
Apply a slight opacity and scale animation to mimic the look of fire.
If using JavaScript/Canvas Animation:
Create a flame animation function that periodically adjusts the flame's properties like position, size, and color.
If using Three.js (for 3D):
Use particle effects or shaders to create a realistic flame effect.
Three.js has particle systems that can be customized to look like fire by controlling particle size, color, opacity, and movement.
WebGL or Shader Approach:
If WebGL is in use, shaders provide a powerful way to create realistic fire animations. You could use fragment shaders to simulate fire textures.
4. Implementing the Animation in Code
After creating the animation (whether in CSS, JavaScript, or using a 3D library), apply it to each torch element in the grid.
Loop over the grid and assign the animation to each torch element, adjusting positions as necessary.
5. Testing and Refining
Test the animation to make sure it doesn’t cause performance issues, especially since it will be applied to multiple elements.
Check the animation’s appearance in different browsers and on various screen sizes to ensure consistency.
6. Documenting Your Work
Document the changes made and any new files or code snippets added. This should go in the project’s documentation or as a comment in the GitHub issue.

**Comment by CristopherAguilar10** [comment]
@jimenezz22 I will open PR

**Comment by jimenezz22** [comment]
> @jimenezz22 I will open PR

 @CristopherAguilar10 awesome, I will check it as soon as you send it
