### ISSUE TITLE
Rename BabySprite files

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarkHack2024FrontEndv2#160]
### Scope
In the path Assets/BabySprites we have some sprite files with ambiguous names, so we need to rename these files for something more meaningful

### How to implement the template?
A good name could be: Penguin-Crystal-Sleep.gif

### How to apply?
Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

**Comment by mimisavage** [comment]
May I pick this up?

**Comment by raizo07** [comment]
Can I take this from here? I'm a Software developer with over 3 years experience

ETA: 5 hours

**Comment by abdegenius** [comment]
I’d love to work on this task.

**Comment by Steph3097** [comment]
Hey! im Sttef and I’m excited to contribute to this project! I have over five years of experience in front-end development, primarily working with React and TypeScript. 
I am part of Dojo Coding
For this task, I propose the following approach:
-Review the file BabySprites
-Define a Naming Convention
-Create a structured and meaningful naming convention following the structure of the repo
- Rename the files while maintaining their references in code or other assets to avoid breaking dependencies.
- Verify that all renamed files are properly integrated and functional in the project, ensuring nothing is missed.
I’d love to bring my expertise and collaborative spirit to this project. Thank you for consider my application!

**Comment by AdejareSamad** [comment]
Could I take over this issue?

**Comment by danielrobotz** [comment]
Can I take this issue?

**Comment by emarc99** [comment]
May I take care of this?

**Comment by obacollins-lab** [comment]
I can take on this right away.

**Comment by GideonBature** [comment]
Could I be assigned to this?

**Comment by ShantelPeters** [comment]
I’d love to work on this task.

**Comment by EmmanuelAR** [comment]
Hello team Im Emmanuel Aguero from Costa Rica, Dojo coding member and Go Stark Me team member.
I will like to work on this issue, i will follow the instructions to create the rename the files
let me know!

**Comment by psychemist** [comment]
Hi. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

I have a very high attention to detail, am allergic to typos, and have a good command of English as a native speaker. I am also an avid gamer and am particular about naking conventions of in-game assets. I would ensure that all the files that need attending to are sorted, leaving nothing out.

I aim to complete this task within 5 hours of being assigned and setting up my development environment.

Thank you for the opportunity and I look forward to working with you.

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by TheSQLguy** [comment]
I would do this to solve the problem

Identify Ambiguous Files: Identify all sprite files with unclear or ambiguous names in the Assets/BabySprites directory.
Rename Files: Apply the naming convention Animal-Theme-Action.gif for the files. For instance, if a file is describing a sleeping penguin by a crystal theme, the file should be renamed to Penguin-Crystal-Sleep.gif.
Update References: Update all references in the Unity project where these sprites are used to change paths to the renamed files so that no broken links are created.
Test Changes: Run the Unity project to ensure that all sprite assets are loaded correctly and that no errors are generated.
Document Changes: Commit the changes with a meaningful message, such as:
makefile
feat: renamed sprite files in BabySprites directory for better clarity
Open a Pull Request with adequate details according to the contribution guideline and clearly state the update names.
This task shall ensure that assets are orderly arranged and development processes eased. Time estimate: about 2 hours.

**Comment by Kom02** [comment]
Hi, I’m Kevin Obando, a full-stack software developer with 2 years of experience. Currently, I’m exploring the world of blockchain and am eager to gain hands-on experience in this field.

**Comment by olisaagbafor** [comment]
Can I handle this task?

**Comment by DuendexCR** [comment]
Can I jump on this task?

**Comment by tosinmoses384** [comment]
Can I tackle this one?

**Comment by pheobeayo** [comment]
Mind if I take this issue?

**Comment by Nityam573** [comment]
Let me handle this issue!

**Comment by psychemist** [comment]
PR #168 raised and ready for review.
